version: '3'

services:
  app:
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=--enable-source-maps
    ports:
      - 9229:9229
    volumes:
      - ./src:/app/src
      - ./dist:/app/dist
      - ./types:/app/types
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./nodemon.json:/app/nodemon.json
      - ./.eslintrc:/app/.eslintrc
      - ./.prettierrc:/app/.prettierrc
      - ./tsconfig.json:/app/tsconfig.json
    command: npm run watch-ts